name: build-docker
description: |
  Builds a docker image and pushes it up
inputs:
  builder:
    description: The name of the builder.
  build-args:
    description: Any build arguments passed to the builder.
  tags:
    description: A list of tags
  target:
    description: The name of the image we're building.
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
      if: ${{ !inputs.builder }}
      id: builder
    - uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.builder.outputs.name || inputs.builder }}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        tags: ${{ inputs.tags }}
        target: ${{ inputs.target }}