name: lint-python
description: Runs the specified linter against the local codebase.
inputs:
  linter:
    description: The pypi package name for the requested linter.
    required: true
  command:
    description: The linter command line arguments
    required: true
runs:
  using: composite
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-python@v4
     with:
       python-version: 3.11
   - name: install ${{ inputs.linter }}
     shell: bash
     run: pip install ${{ inputs.linter }}
   - name: lint with ${{ inputs.linter }}
     shell: bash
     run: ${{ inputs.command }}