name: lint-python
description: Runs the specified linter against the local codebase
inputs:
  package:
    description: The Pypi package name for the requested linter.
    required: true
  command:
    description: The command for the requested linter
    required: true
outputs:
  report:
    description: The number of issues and how many will remain after.
    value: ${{ steps.run.outputs.report }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - id: install
      shell: bash
      run: pip install ${{ inputs.package }}
    - id: run
      shell: bash
      run: |
        