name: ruff
description: Runs the ruff linter against the local codebase.
runs:
  using: composite
  steps:
   - uses: actions/checkout@v4
   - uses: actions/setup-python@v4
     with:
       python-version: 3.11
   - name: install ruff
     shell: bash
     run: pip install ruff
   - name: lint with ruff
     shell: bash
     run: |
      echo ruff check --exit-non-zero-on-fix --fix ${{ github.workspace }} && /bin/false