name: mega-lint
description: Runs the specified linter against the local codebase.
inputs:
  linter:
    description: The name of the requested linter.
    required: true
  action:
    description: Whether or not to automatically format with the specified linter.
    required: true
outputs:
  fixable:
    description: The number of lints the linter can fix.
    value: ${{ steps.run.outputs.fixable }}
  remaining:
    description: The number of lints the linter cannot fixable.
    value: ${{ steps.run.outputs.remaining }}
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with: 
        node-version: 18.x
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - id: run
      shell: bash
      run: ${{ github.action_path }}/${{ inputs.linter }}.sh ${{ inputs.action }}