name: lint-python
description: Runs the specified linter against the local codebase.
inputs:
  type:
    description: "The type of linter in question: Valid choices ['python', 'node']."
    required: false
    default: python
  linter:
    description: The pypi package name for the requested linter.
    required: true
  command:
    description: The linter command line arguments
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - if: ${{ inputs.type == 'node' }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - if: ${{ inputs.type == 'node' }}
      shell: bash
      run: npm install ${{ inputs.linter }} && ${{ inputs.command }}
    - if: ${{ inputs.type == 'python' }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - if: ${{ inputs.type == 'python' }}
      shell: bash
      run: |
        pip install ${{ inputs.linter }}
        ${{ inputs.command }}