name: lint-python
description: Runs the specified linter against the local codebase.
inputs:
  linter:
    description: The name of the requested linter.
    required: true
  action:
    description: Whether or not to automatically format with the specified linter.
    required: true
outputs:
  report:
    description: |
      A JSON Object containing two keys "fixable" and "remaining" whose values
      correspond to the number of lint violations that the linter considers
      fixable, and the number of lints that would remain after fixed had been
      applied to the local repository.
    value: ${{ steps.run.outputs.report }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with: 
        node-version: 18.x
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - id: run
      shell: bash
      run: ${{ github.action_path }}/${{ inputs.linter }}.sh ${{ inputs.action }}