name: lint-ruff
description: Lint the local repository with [ruff](https://beta.ruff.rs)
outputs:
  report:
    description: | 
      JSON formatted output report of the number of errors and how many would
      remain after fixing.
    value: ${{ steps.ruff.outputs.report }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - id: ruff
      shell: bash
      run: |
        pip install ruff
        ruff check --format json . | jq 'group_by(.fix | type) | map({(if .[0].fix == null then "not-fixable" else "fixable" end ): length}) | add'