name: build-node
description: |
  Builds a docker image and pushes it up
inputs:
  directory:
    required: true
    description: The directory containing the node package we're building.
  target:
    required: true
    description: |
      The S3 bucket to push to. In green/blue deployments, it's the bucket not
      currently being used by the blue environment.
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: ${{ inputs.directory }}/
    - uses: borales/actions-yarn@v4
      with:
        cmd: build
        dir: ${{ inputs.directory }}/
    - shell: bash
      run: aws s3 sync ${{ inputs.directory }}/dist/ ${{ inputs.target }}