name: test-runner
description: Runs a test suite
inputs:
  suite:
    description: The name of the test runner.
    required: true
  cache-path:
    description: A list of files, directories, and wildcard patterns to cache and restore.  
    required: true
  cache-key:
    description: An explicit key for a cache entry.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key}}
        restore: ${{ inputs.cache-key }}
    - if: ${{ inputs.suite == 'python' }}
      uses: actions/install-python@v4
      with:
        python-version: 3.9
    - if: ${{ inputs.suite == 'python' }}
      uses: snok/install-poetry@v1
    - if: ${{ inputs.suite == 'node' }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - if: ${{ inputs.suite == 'node' }}
      uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: "front-end/"
    - shell: bash
      run: ${{ github.action_path }}/${{ inputs.suite }}.sh