on: 
  workflow_call:
jobs:
  front-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: front-end/
      - uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: front-end/
  base-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: builder
        uses: docker/setup-buildx-action@v2
      - name: build intermediate images
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.builder.outputs.name }}
          target: builder
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: echo "Prepare"
  docker:
    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
       artifact: ["api", "bit-runner", "task-scheduler"]
    name: ${{ matrix.artifact }}
    steps:
      - run: |
          echo "BUILD: ${{ matrix.artifact }}"
  publish:
    needs: [front-end, docker]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PUBLISH: ${{ matrix.artifact }}"
    
  