on: 
  - push
jobs:
  lint:
    strategy:
      matrix:
        linter:
          - package: ruff
            command: ruff check --fix --exit-non-zero-on-fix ${{ github.workspace }}
    uses: ./.github/workflows/lint-python.yml
    with:
      linter: ${{ matrix.linter.package }}
      command: ${{ matrix.linter.command }}