on: 
  push:
    branches: ["main"]
jobs:
  lint-ruff:
    uses: ./.github/workflows/lint-python.yml
    with:
      linter: ruff
  fix-if-failed:
    needs: 
      - lint-ruff
    uses: ./.github/workflows/reusable.yml
    with:
      message: "HELLO! ${{ failure() }}"