on: 
  - push
jobs:
  test:
    uses: ./.github/workflows/test.yml
  lint:
    uses: ./.github/workflows/lint.yml
  format:
    needs: [lint, test]
    if: ${{ failure('lint') && !failure('test') }}
    uses: ./.github/workflows/format.yml
    secrets: inherit
    permissions:
      contents: write
  build:
    runs-on: ubuntu-latest
    needs: [format]
    if:  ${{ always() && !failure('lint') && !failure('test') }}
    steps:
      - run: echo "BUILD"
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && !failure('build') }}
    steps:
      - run: echo "DEPLOY"