on: 
  - push
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  format:
    needs: [lint]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "WTF"
          echo ${{ needs.lint.result }}
