on: 
  - push
jobs:
  test:
    if: ${{ 1 == 2 }}
    uses: ./.github/workflows/test.yml
  lint:
    uses: ./.github/workflows/lint.yml
  format:
    needs: [lint]
    if: ${{ failure('lint') }}
    uses: ./.github/workflows/format.yml
    secrets: inherit
    permissions:
      contents: write
  build:
    runs-on: ubuntu-latest
    needs: [format]
    if:  ${{ always() && jobs.format.status != "failure" }}
    steps:
      - run: echo "BUILD"
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "DEPLOY"