name: CI
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/test.yml
  lint:
    uses: ./.github/workflows/lint.yml
  format:
    needs: [lint, test]
    if: ${{ failure('lint') && !failure('test') && github.branch != 'main' }}
    uses: ./.github/workflows/format.yml
    secrets: inherit
    permissions:
      contents: write
  build:
    if:  ${{ always() && !failure('lint') && !failure('test') }}
    uses: ./.github/workflows/build.yml
    needs: [format]
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && success() && github.branch == 'main' }}
    steps:
      - run: echo "DEPLOY"