on: 
  - push
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  format:
    needs: [lint]
    if: ${{ failure('lint') }}
    uses: ./.github/workflows/lint.yml
    with:
      format: true