on:
  workflow_call:
    inputs:
      committer-name:
        type: string
        default: "[bot] rosie"
      committer-email:
        type: string
        default: "rosie@drill.run"
jobs:
   format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ruff
        continue-on-error: true
        name: format ruff
        uses: ./.github/actions/mega-lint
        with:
          linter: ruff
          action: format
      - id: black
        continue-on-error: true
        name: format black
        uses: ./.github/actions/mega-lint
        with: 
          linter: black
          action: format
      - id: remainder
        run: |
          echo "${{ fromJSON(steps.*.outputs.report) }}" | jq 'select(.remaining) | length'
          echo remaining=10 >> $GITHUB_OUTPUT
      - run: echo "Run Tests"
      - run: |
          echo "${{ fromJSON(steps.remainder.outputs.remaining) }}"