on:
  workflow_call:
    inputs:
      commit-message-header:
        type: string
        default: Automatic update with format changes from linters.
      committer-name:
        type: string
        default: "[bot] rosie"
      committer-email:
        type: string
        default: "rosie@drill.run"
jobs:
   format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ruff
        continue-on-error: true
        name: format ruff
        uses: ./.github/actions/mega-lint
        with:
          linter: ruff
          action: format
      - id: black
        continue-on-error: true
        name: format black
        uses: ./.github/actions/mega-lint
        with: 
          linter: black
          action: format
      - id: prepare
        run: fixable=$( echo "${{ join(steps.*.outputs.fixable) }}" | jq 'fromjson | add' 
      - run: echo "Run Tests"
      -  run: |
          echo "WOULD COMMIT"
          echo "${{ steps.*.outputs.fixable >= 1 }}"

