on:
  workflow_call:
    inputs:
      commit-message-header:
        type: string
        default: Automatic update with format changes from linters.
      committer-name:
        type: string
        default: "[bot] rosie"
      committer-email:
        type: string
        default: "rosie@drill.run"
jobs:
   format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ruff
        continue-on-error: true
        name: format ruff
        uses: ./.github/actions/mega-lint
        with:
          linter: ruff
          action: format
      - id: black
        continue-on-error: true
        name: format black
        uses: ./.github/actions/mega-lint
        with: 
          linter: black
          action: format
      - id: prepare
        run: |
          CHANGES=$(git status -s | wc -l )
          REMAINING=$(sed -e 's/^[[:space:]]*,*/[/' -e 's/,,*/,/g' -e 's/,*$/]/' <<-EOF
          ${{ join(steps.*.outputs.remaining) }}
          EOF
          );

          echo changes=${CHANGES} >> $GITHUB_OUTPUT
          echo remaining=$(echo ${REMAINING} | jq 'add') >> $GITHUB_OUTPUT
          echo 'commit-message<<EOF' >> $GITHUB_OUTPUT
          echo '${{ inputs.commit-message-header }}' >> $GITHUB_OUTPUT
          echo >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - uses: ./.github/actions/test-runner
        with:
          suite: python
          cache-path: .venv
          cache-hash-pattern: "**/poetry.lock"
      - if: ${{ steps.prepare.outputs.changes >= 1 }} 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: "-u ':!**/poetry.lock' ':!**/yarn.lock'"
          commit_user_name: ${{ inputs.committer-name }}
          commit_user_email: ${{ inputs.committer-email }}
          commit_message: ${{ steps.prepare.outputs.commit-message }}
      - if: ${{ steps.prepare.outputs.changes >= 1 }}
        run: /bin/false