on:
  workflow_call:
    inputs:
      commit-message-header:
        type: string
        default: Automatic update with format changes from linters.
      committer-name:
        type: string
        default: "[bot] rosie"
      committer-email:
        type: string
        default: "rosie@drill.run"
jobs:
   format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ruff
        continue-on-error: true
        name: format ruff
        uses: ./.github/actions/mega-lint
        with:
          linter: ruff
          action: format
      - id: black
        continue-on-error: true
        name: format black
        uses: ./.github/actions/mega-lint
        with: 
          linter: black
          action: format
      - run: echo "Run Tests"
      - id: results
        run: |
          echo ruff -> ${{ contains(steps.ruff.outputs.report, 'fixable') }}

          LINT_RESULT=$(
            echo "${{ toJSON(steps.*.outputs.report) }}" |
              jq 'map(fromjson | to_entries[]) 
                    | group_by(.key) 
                    | map({(.[0].key): length}) 
                    | add'
          )

          REMAINING=$(echo $LINT_RESULT | jq '.remaining')
          FIXABLE=$(echo $LINT_RESULT | jq '.fixable')

          echo "remaining=${REMAINING}" >> $GITHUB_OUTPUT
          echo "fixable=${FIXABLE}" >> $GITHUB_OUTPUT
          echo "linters-with-fixes=" >> $GITHUB_OUTPUT
      - id: push-changes
        name: push changes
        if: ${{ steps.results.outputs.fixable >= 1 }}
        run: |
          git config --global user.name "${{ inputs.committer-name }}"
          git config --global user.email "${{ inputs.committer-email }}"
          git status
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git add -u
          git commit -F- <<EOF
          ${{ inputs.commit-message-header}}

            * black
            * ruff

          Signed-off-by: ${{ inputs.committer-name }} <${{ inputs.committer-email }}>
          EOF
          git push

      - id: fail-on-remaining
        if: ${{ steps.results.outputs.remaining >= 1 }}
        run: /bin/false