on:
  workflow_call:
    inputs:
      committer-name:
        type: string
        default: "[bot] rosie"
      committer-email:
        type: string
        default: "rosie@drill.run"
jobs:
   format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ruff
        continue-on-error: true
        name: format ruff
        uses: ./.github/actions/mega-lint
        with:
          linter: ruff
          command: ruff check --format json --fix . | jq '"remaining=1"'
      - run: echo "Run Tests"
      - run: |
          echo "${{ fromJson(steps.ruff.outputs) }}"
          git config --global user.name ${{ inputs.committer-name }}
          git config --global user.email ${{ inputs.committer-email }}
