on:
  workflow_call:
jobs:
   format:
    runs-on: ubuntu-latest
    steps:
      - id: ruff
        run: echo "Would format with ruff"
      - id: black
        run: echo "Would format with black"
      - id: prettier
        run: echo "Would format with prettier"
      - run: echo "WOULD FORMAT"