on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linters:
          - name: name
            action: ./.github/actions/linters/ruff
    name: lint ${{ matrix.linters.name }}
    steps:
      - uses: actions/checkout@v3
      - id: lint
        uses: ${{ matrix.linters.action }}
      - run: /bin/false