on:
  workflow_call:
  
jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        linters:
            - name: ruff
            - name: black
    runs-on: ubuntu-latest
    name: lint ${{ matrix.linters.name }}
    steps:
      - uses: actions/checkout@v3
      - id: lint
        uses: ./.github/actions/mega-lint
        with:
          linter: ${{ matrix.linters.name }}
          action: check