on:
  workflow_call:
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - id: ruff
        uses: ./.github/actions/lint-python
        continue-on-error: true
        with:
          linter: ruff
          command: ruff check --verbose --fix --exit-non-zero-on-fix . 
      - id: black
        uses: ./.github/actions/lint-python
        continue-on-error: true
        with:
         linter: black
         command: black --check . || (black . && /bin/false)
      - id: vue
        continue-on-error: true
        run: echo "LINT and format Vue"
      - uses: ./.github/actions/commit-changes
        if: ${{ failure() }}
        with:
          failed: ruff=${{ steps.ruff.outcome }},black=${{steps.black.outcome}},vue=${{steps.vue.outcome}}
          repo: ${{ github.repository }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}