name: publish
on: 
  workflow_call:
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        artifact: ["api", "front-end"]
    steps:
      - run: echo ${{ matrix.artifact }}
    
           