on:  
  workflow_call:
    
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: 
          - name: "python"
            cache:
              path: .venv
              key: poetry-${{ hashFiles('**/poetry.lock') }}-${{ env.pythonLocation }}
          - name: "node"
            cache:
              path: .front-end/node_modules/
              key: yarn-${{ hashFiles('**/yarn.lock') }}
    name: ${{ matrix.suite }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./github/actions/test-runner
        with:
          suite: ${{ matrix.suite.name }}
          cache: ${{ matrix.suite.cache-path }}