on:  
  workflow_call:
jobs:
  test-python:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: snok/install-poetry@v1
     - uses: actions/cache@v3
       id: cache
       with:
         path: .venv/
         key: poetry-${{ hashFiles('**/poetry.lock') }}-${{ env.pythonLocation }}
         restore-keys: |
           poetry-${{ hashFiles('**/poetry.lock') }}-${{ env.pythonLocation }}