name: build-yarn-bundle
description: |
  builds our front-end bundle for publishing to s3.
inputs:
  target:
    description: The name of the target image from the Dockerfile.
    required: true
  dir:
    description: The name of the directory to chdir into.
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - uses: borales/actions-yarn@v4.2.0
      with:
        cmd: install
        dir: ${{ inputs.dir }}
    - uses: borales/actions-yarn@v4.2.0
      with:
        cmd: build
        dir: ${{ inputs.dir }}
    - shell: bash
      run: |
        aws s3 sync ${{ inputs.dir }}/dist/ s3://app.drill.run-production-green
        